apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra
  name: cassandra
spec:
  type: NodePort
  ports:
    - port: 9042
      name: cql
    - port: 9160
      name: thrift
  selector:
    name: cassandra
