apiVersion: v1
kind: ReplicationController
metadata:
  name: edge
  labels:
    name: edge
spec:
  replicas: 1
  selector:
    name: edge
  template:
    metadata:
      labels:
        name: edge
    spec:
      containers:
        - name: edge
          image: hora/recipes-rss-edge-kieker:0.3
          ports:
            - containerPort: 9090
