apiVersion: v1
kind: ReplicationController
metadata:
  name: edge-kieker
  labels:
    name: edge-kieker
spec:
  replicas: 1
  selector:
    name: edge-kieker
  template:
    metadata:
      labels:
        name: edge-kieker
    spec:
      containers:
        - name: edge-kieker
          image: hora/recipes-rss-kieker-edge:0.3
          ports:
            - containerPort: 9090
