apiVersion: v1
kind: ReplicationController
metadata:
  name: middletier
  labels:
    name: middletier
spec:
  replicas: 1
  selector:
    name: middletier
  template:
    metadata:
      labels:
        name: middletier
    spec:
      containers:
        - name: middletier
          image: hora/recipes-rss-middletier-kieker:0.3
          ports:
            - containerPort: 9191
